spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  resources:
    static-locations: classpath:/

server:
  port: 8084

